In [2]:
import pandas as pd
df = pd.read_excel("C:/Users/Akschaya balaji/Downloads/death.xlsx")
df.head()

,patient_id,gender,education,treatment_data,id_healthcenter,id_treatment_region,hereditary_history,birth_date,age,weight,...,taking_gallbladder_disease_medicine,smoking,alcohol,breast_pain,radiation_history,Birth_control(Contraception),\nmenstrual_age,\nmenopausal_age,\nBenign_malignant_cancer,condition
0,111036008041,0,4,2019,1110000256,1110000329,1,1989,30,69,...,1,0,0,1,1,1,1,0.0,1,death
1,111035996130,0,6,2019,1110000316,1110000331,0,1989,30,71,...,1,0,1,0,0,0,2,0.0,0,death
2,111035971333,0,5,2019,1110000288,1110000330,0,1989,30,74,...,0,0,0,1,1,0,1,0.0,1,death
3,111036018485,0,5,2019,1110000042,1110000329,1,1989,30,75,...,1,1,0,0,0,0,2,0.0,0,death
4,111035985474,0,1,2019,1110000116,1110000330,0,2009,10,70,...,0,0,0,0,0,0,0,0.0,0,death

Explanatory variables:
1.age
2.Weight
3.taking_gallbladder_disease_medicine	
4.smoking
5.alcohol
6.breast_pain	
7.radiation_history 

response variable:
1.Benign_malignant_cancer
2.condition